### ISSUE TITLE
Random disconnects

### ISSUE THREAD

**Issue by FreeBear-nc** [olegtarasov/esphome-opentherm#15] opened 2024-11-13 02:39 UTC
Just a heads up.
Have been running the opentherm component now that it has been fully merged in to esphome. Left it running this evening and have been experiencing random disconnects. Have failed to record any meaningful messages, but did see something flash past suggesting at least one event was triggered by an exception - This _might_ be a result of using `sync_mode: true` - Certainly getting a lot of warnings about `Component opentherm took a long time for an operation (216 ms)`. Perhaps the watchdog is biting, not sure...
Unfortunately, my time is limited during the week, so won't have time to dive in deeper until the weekend. Hope to capture a crash dump using https://github.com/dentra/esphome-components/tree/master/components/crash_info

**Comment by tbrasser** [comment] 2024-11-14 16:21
Similar issue here, as soon as I add documented sensors and binary sensors it just goes offline afyer a while. I'm not using sync_mode

**Comment by olegtarasov** [comment] 2024-11-14 17:53
I'm experiencing random disconnects myself, but I didn't have time to get to the bottom of the issue. I decided that it could be an issue with cheap dev boards I'm using, or some other fluke. I'm using this component for over a year now and these disconnects seem to be harmless and don't affect my boiler. If anyone gets to the root cause of why this is happening, I would be happy to fix the problem if it indeed comes from this component.

**Comment by FreeBear-nc** [comment] 2024-11-14 23:12
Looking at my HA logs, the disconnects appear randomly between 1min39sec and 50min periods. Whilst the boiler is running, these disconnects cause a shutdown of 1 to 4 minutes duration. On starting up, the boiler runs at full (rate limited) power for ~30 seconds - This is wasteful of gas and puts undue stress on the mechanical components. So to my mind, undesirable and impacts on efficiency & long term reliability.
Have extended the OT cable so that I can run the ESP32 on the bench with a JTAG debugger attached - Will attempt to do some work on it over the weekend.

**Comment by olegtarasov** [comment] 2024-11-15 06:05
@FreeBear-nc It seems your boiler reacts differently than mine :( I've just initiated a forced restart while boiler was running, and flame did switch off for 1-2 seconds, but switched back on almost immediately. I think that's why I don't notice these effects. I've also checked HA logs and saw just one disconnect in a course of several days. So it would be great if you could catch this problem on your end, since it doesn't seem to appear all that often for me.

As a side note, do you experience the same disconnects with your version of the component based on original Arthur Rump's repo?

**Comment by tbrasser** [comment] 2024-11-15 09:55
Are you running with a lot of sensors enabled? Seems it's more stable with fewer things enabled like in the example.

**Comment by olegtarasov** [comment] 2024-11-15 10:05
I have 8-9 sensors in my config, since my boiler doesn't support much of the OpenTherm spec. Normally, the number of sensors shouldn't affect stability as each esphome loop iteration sends only one message at a time.
Maybe your disconnects happen because you are using ESP8266 and not ESP32. This component wasn't thoroughly tested on ESP8266 and I generally recommend using ESP32.

**Comment by tbrasser** [comment] 2024-11-15 11:26
Let me swap to an esp32 and report back (will try to not hijack threads, but also didn't want to create duplicates, let me know what you prefer)

edit: using esp32 seems to have solved my instability issues, thanks for the tip!

**Comment by FreeBear-nc** [comment] 2024-11-15 14:41
> As a side note, do you experience the same disconnects with your version of the component based on original Arthur Rump's repo?

No disconnects using Arthur's code - Using my own fork with a current version of Ihor Melnyk's OT library on a Wemos D1 mini (ESP8266 based). Have a selection of other boards I _could_ try, but I'd rather get to the bottom of this problem as I suspect many users will also be using the D1 mini.

**Comment by FreeBear-nc** [comment] 2024-11-15 14:47
> Let me swap to an esp32 and report back (will try to not hijack threads, but also didn't want to create duplicates, let me know what you prefer)

Lets keep to one thread rather than spreading the same issue across multiple reports.
Whilst I can drop an ESP32 board in (have S2 and C3 variants), it doesn't help D1-mini users.

**Comment by FreeBear-nc** [comment] 2024-11-16 20:18
OK. Identified the exception - `Unhandled C++ exception: OOM`
The culprit is stringstream in debug_data() and possibly debug_error(). Setting debugging level higher than DEBUG doesn't fix the problem. Have reworked the print statements, and will generate a PR shortly.

Still not fixed the problem - Am now getting an illegal instruction in start_read_timer(). After removing the crash_info component, the illegal instruction has moved to verify_stop_bit().

**Comment by FreeBear-nc** [comment] 2024-11-17 00:42
> Still not fixed the problem - Am now getting an illegal instruction in start_read_timer().

Removing the crash_info* component seems to have fixed the illegal instruction (subject to further monitoring).

*) https://github.com/dentra/esphome-components/tree/master/components/crash_info

**Comment by FreeBear-nc** [comment] 2024-11-18 00:14
> Still not fixed the problem - Am now getting an illegal instruction in start_read_timer(). After removing the crash_info component, the illegal instruction has moved to verify_stop_bit().

Looks like the illegal instruction is caused by a faulty flash chip - Currently running on an ESP32-C3 board (with PR18 mods), and no errors yet. Have ordered some more D1-mini boards (both ESP32 and ESP8266 variants) and an ESP32-S3 for further testing. It will be about a week before they arrive.

**Comment by olegtarasov** [comment] 2024-11-18 17:06
@FreeBear-nc Thank you for doing such an awesome debugging job! I've also received a ESP8266 board and plan to run my own boiler with it starting from this weekend.

**Comment by FreeBear-nc** [comment] 2024-11-24 17:00
Been running with an ESP32-C3 over the last week without any crashes. New ESP8266 boards turned up yesterday. Still getting crashes from illegal instructions. Have been digging for answers, and am currently running with a provisional fix.

**Comment by FreeBear-nc** [comment] 2024-11-25 11:57
#18 and #21 appear to have solved the random disconnects. On an esp8266, exceptions would have been triggered within an hour or two. None seen over the last 12 hours, but will monitor for a few days before closing this issue.

**Comment by olegtarasov** [comment] 2024-11-25 12:19
@FreeBear-nc Thank you for such a great work debugging this problem! I will propose a new PR to esphome with the most critical changes later today.

**Comment by FreeBear-nc** [comment] 2024-11-26 00:39
Reviewed HA history over the last week when I had been using an ESP32-C3. Disconnects were still happening after 10-70 hours of running. No logs saved to verify if it was an illegal instruction, although I suspect it was.
Raised a PR with esphome as it appears the relevant patch got dropped from PR7835.

24 hours running on a new esp8266 board (with all fixes applied). No disconnects to report :)

**Comment by olegtarasov** [comment] 2024-11-26 05:52
I have a similar situation with vanilla ESP32: disconnects don't happen frequently, but they still appear. Will flash a fix with `IRAM_ATTR` and see what happens. `verify_stop_bit_` and `check_parity_` are used on ESP32 as well, so there is a real chance those crashes will be solved.

**Comment by olegtarasov** [comment] 2024-11-28 06:03
Both fixes got merged to esphome. I also pushed `v1.0.4` to this repo, which contains the fix. Closing this issue for now. @tbrasser feel free to reopen if you are still experiencing disconnects after applying the fix.

**Closed as completed by olegtarasov** 2024-11-28 06:03 UTC

**Comment by tbrasser** [comment] 2024-11-28 07:38
I can swap back in my esp8266 but current esp32 is running fine :)

**Comment by FreeBear-nc** [comment] 2024-11-28 10:53
Got the following in my logs this morning. Wasn't connected via USB, so failed to capture all the gory details of the crash.

```
[debug:056]: Reset Reason: Exception
[debug:057]: Reset Info: Fatal exception:28 flag:2 (Exception) epc1:0x4000debe epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
[text_sensor:064]: 'Device Info': Sending state '2024.12.0-dev|Flash: 4096kB Speed:40MHz Mode:DOUT|Chip: 0x0057b618|SDK: 2.2.2-dev(38a443e)|Core: 3.1.2|Boot: 6|Mode: 1|CPU: 80|Flash: 0x00164068|Reset: Exception|Fatal exception:28 flag:2 (Exception) epc1:0x4000debe epc2:0x00000000 epc3:0x00000000 excvadd'
[text_sensor:064]: 'Reset Reason': Sending state 'Exception'
[crash_info:061]: Reset Reason: Exception
[crash_info:067]: Crash info: 
[crash_info:073]:   Exception cause code: 28
[crash_info:078]:   Stacktrace:
[crash_info:096]:      40235879 40219e51 40101322 4021a199
[crash_info:096]:      40101322 40219128 4022b090 4022a948
```
